export const reviewsText = [
	"This place is amazing, it has some of the best dishes in the world. It is so so so good!!!",
	"This food is so good! It is the fanciest thing I have ever seen in my short life",
	"Excellent food and service. Busy night, but everything was great! Highly recommend.",
	"Very nice place for a date night, the service was fast and friendly. The food was amazing.",
	"Extremely disappointing in our experience.",
	"This place is amazing, it has some of the best dishes in the world. It is so so so good!!!",
	"Very nice evening spent with special family.",
	"As always, food was excellent. Waitress was friendly and prompt. We had just one problem in that our dessert order went rogue in the system and we waited ages for it to arrive.",
	"Fantastic food and excellent selection. Everything was fresh - and the scones were still warm!",
	"Food was served cold. Major No No. Fantastic Dessert. Service was good. Heavy Rock music should be toned down. Price vs Quality… not great.",
	"It was really great! Just temperature wise it was really chilly. A little mixup at the end with desserts also but overall we really enjoyed the evening",
	"The steaks were 'Melt In Your Mouth'!!! Nigel, our waiter was amazing!! Great experience overall!",
	"The food was absolutely on point, we had such a great experience and our server was top notch.",
	"Enjoyed our drinks, dinner and dessert. Great service and ambience.",
	"Very nice evening spent with special family.",
	"Had a full 3 course meal in the mid afternoon and every aspect of it was great. Server was named Brittany I believe and she was simply excellent.",
	"This visit was with a friend who had never been here before. She loved it as much as I do. She said it will be our new go to place!",
	"Prime rib and filet were made spot on. Vegetable sides were made well as was the shrimp and scallops.",
	"Wonderful service! Delicious food! Comfortable seating and luxurious atmosphere.",
];

export const users = [
	{
		id: "410544b2-4001-4271-9855-fec4b6a6442a",
		first_name: "Laith",
		last_name: "Harb",
		email: "laith@hotmail.com",
		city: "ottawa",
		password: "cdhnklewlcf",
		phone: "1112223333",
		created_at: new Date(),
		updated_at: new Date(),
	},
	{
		id: "3958dc9e-712f-4377-85e9-fec4b6a6442a",
		first_name: "Josh",
		last_name: "Allen",
		email: "josh@hotmail.com",
		city: "toronto",
		password: "Wieslawa69",
		phone: "1112223333",
		created_at: new Date(),
		updated_at: new Date(),
	},
	{
		id: "3958dc9e-737f-4377-85e9-fec4b6a6442a",
		first_name: "LeBron",
		last_name: "James",
		email: "lebron@hotmail.com",
		city: "niagara",
		password: "dwecf",
		phone: "1112223333",
		created_at: new Date(),
		updated_at: new Date(),
	},
	{
		id: "3958dc9e-787f-4377-85e9-fec4b6a6442a",
		first_name: "Cassidy",
		last_name: "Marksom",
		email: "cassidy@hotmail.com",
		city: "toronto",
		password: "dwecf",
		phone: "1112223333",
		created_at: new Date(),
		updated_at: new Date(),
	},
];
